version: '2'
services:
  ssh-honeypot:
    image: 'local/ssh-honeypot:latest'
    build:
        context: ../
        dockerfile: docker/Dockerfile
    ports:
      - '22:2022'
    volumes:
      - log:/home/honeycomb/log
      - rsa:/home/honeycomb/rsa     
    networks:
      default: 
    restart: unless-stopped

volumes:
  log:
    driver: local
  rsa:
    driver: local

networks:
  default:
